api:
  key: C063DE8FADEB47EFB26DB3534BDE6A3C
plugins:
  DisplayLayerProgress:
    navBarMessagePattern: |-
      Progress: <span style='display: inline-block;width:24px;'>[progress]%</span>
      Layer: <span style='display: inline-block;width:24px;'> [current_layer]</span> of
      <span style='display: inline-block;width:24px;'>[total_layers]</span>
      Height: <span style='display: inline-block;width:42px;'>[current_height]</span> of
      <span style='display: inline-block;width:42px;'>[fanspeed]</span>mm
    printerDisplayMessagePattern: Progress:[progress]% Layers:[current_layer]/[total_layers]
    printerDisplayScreenLocation: '"dir1": "up", "dir2": "right", "firstpos1": 40,
      "firstpos2": 40, "spacing1": 0, "spacing2": 0'
    printerDisplayWidth: 20%
    secondPrinterDisplayMessagePattern: 'Nozzle: [current_tool0_temp] Bed:[current_bed_temp]
      Fan Speed :[fanspeed]'
    toggleDisplayDelay: '7'
    togglePrinterDisplayEnabled: true
    updatePrinterDisplayWhilePrinting: true
  PrintJobHistory:
    capturePrintJobHistoryMode: always
    currencySymbol: $
    lastPluginDependencyCheck: 1.17.3
    pluginCheckActivated: false
  Spoolman:
    selectedSpoolIds:
      '0':
        spoolId: '2'
    spoolmanUrl: http://spoolman:8000
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1670938200
      _important:
        read_until: 1698310200
      _octopi:
        read_until: 1746515700
      _plugins:
        read_until: 1752364800
      _releases:
        read_until: 1666085100
    enabled_channels:
    - _plugins
    - _octopi
  autobim:
    has_ubl: true
    probe_points:
    - x: '30'
      y: '30'
    - x: '30'
      y: '186'
    - x: '188'
      y: '186'
    - x: '186'
      y: '30'
  bedlevelvisualizer:
    _config_version: 1
    command: "G28       ; home all axes\nM420 S0   ; Turning off bed leveling while
      probing, if firmware is set\n          ; to restore after G28\nM155 S30  ; reduce
      temperature reporting rate to reduce output pollution\n;M190 S65  ; (optional)
      wait for the bed to get up to temperature\nG29 P1    ; automatically populate
      mesh with all reachable points\nG29 P3    ; infer the rest of the mesh values\nG29
      P3    ; infer the rest of the mesh values again\n@BEDLEVELVISUALIZER\t; tell
      the plugin to watch for reported mesh\nM420 S1 V ; enabled leveling and report
      the new mesh\nG29 S0    ; Save UBL mesh points to slot 0 (EEPROM).\nG29 F 10.0
      ; Set Fade Height for correction at 10.0 mm.\nG29 A     ; Activate the UBL System.\nM500
      \     ; save the current setup to EEPROM\nM155 S3   ; reset temperature reporting\n;M140
      S0   ; cooling down the bed"
    commands:
    - command: ''
      confirmation: false
      enabled_while_graphing: false
      enabled_while_printing: false
      icon: fas fa-gear
      input: []
      label: ''
      message: ''
      tooltip: ''
    descending_y: true
    mesh_timestamp: 8/5/2025, 6:20:54 PM
    show_stored_mesh_on_tab: true
    showdegree: true
    stored_mesh:
    - - 0
      - -0.03
      - -0.04
      - -0.09
      - -0.02
    - - -0.03
      - -0.05
      - -0.07
      - -0.07
      - -0.05
    - - -0.07
      - -0.09
      - -0.1
      - -0.12
      - -0.07
    - - -0.09
      - -0.09
      - -0.11
      - -0.13
      - -0.04
    - - -0.03
      - -0.06
      - -0.04
      - -0.08
      - -0.01
    stored_mesh_x:
    - 25
    - 66
    - 107
    - 147
    - 188
    stored_mesh_y:
    - 25
    - 65
    - 106
    - 146
    - 186
    stored_mesh_z_height: 250
    use_relative_offsets: true
  classicwebcam:
    _config_version: 1
    snapshot: http://127.0.0.1:8080/?action=snapshot
    stream: /webcam/?action=stream
  consolidate_temp_control:
    resize_navbar: false
  costestimation:
    _config_version: 4
    useFilamentManager: false
  cura:
    cura_engine: null
  discovery:
    publicPort: 80
    upnpUuid: 821d45c6-6e18-4ca0-81a2-a724a1fb7dae
  errortracking:
    unique_id: cf6b49b0-75a4-4e43-856e-9d731af8550c
  firmwareupdater:
    _config_version: 3
    _selected_profile: 0
    has_bftcapability: true
    profiles:
    - _id: 0
      _name: Default
      avrdude_avrmcu: m1284p
      avrdude_path: /usr/bin/avrdude
      avrdude_programmer: arduino
      flash_method: avrdude
  gcodeviewer:
    _config_version: 1
  homeassistant:
    _config_version: 2
    node_id: e1184f54ba23401ca75b96f4780d9b9b
    unique_id: e1184f54-ba23-401c-a75b-96f4780d9b9b
  mqtt:
    broker:
      password: N1mbl3Sh@rk
      retain: false
      url: mqtt_docker
      username: gbdineen
    publish:
      metadataActive: true
      printerData: true
  mqttpublish:
    _config_version: 2
    enableGCODE: true
    enableM117: true
    menugroupat: '2'
    topicM117: octoPrint/M117/message
    topics:
    - confirm: false
      icon: icon-home
      label: Tesst Commands
      publishcommand: testmessage
      retained: false
      topic: commands/tests
    - confirm: false
      icon: icon-home
      label: M117
      publishcommand: '{"M117":"Test from M117"}'
      retained: false
      topic: octoPrint/M117/message
  mqttsubscribe:
    _config_version: 3
    api_key: 7vTO1eb-XIB1v8wlEDu2nXQfYEBbop0qLbqZvkhMXaQ
  pi_support:
    ignore_default_password: true
    ignore_undervoltage_on_printstart: true
  pluginmanager:
    repository_restricted: false
  prusaslicerthumbnails:
    align_inline_thumbnail: true
    inline_thumbnail: true
    inline_thumbnail_position_left: true
    resize_filelist: true
    scale_inline_thumbnail: true
    sync_on_refresh: true
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: true
    unique_id: a9562b78-91ce-49b4-8ed0-671df47150fd
  uicustomizer:
    filesFullHeight: false
    gcodeZoom: 1
    mainTabs:
    - - tab_plugin_consolidate_temp_control_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    - - tab_plugin_prettygcode_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    - - tab_plugin_bedlevelvisualizer_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    - - term_link
      - true
      - false
      - fas fa-terminal
      - true
      - false
    - - timelapse_link
      - false
      - false
      - fas fa-film
      - true
      - false
    - - gcode_link
      - false
      - false
      - fab fa-codepen
      - true
      - false
    - - tab_plugin_PrintJobHistory_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    rows:
    - _00#connection_wrapper: true
      _01#state_wrapper: true
      _02#files_wrapper: true
      _03#sidebar_plugin_firmware_check_warning_wrapper: false
      _04#sidebar_plugin_firmware_check_info_wrapper: false
      _05#sidebar_plugin_Spoolman_wrapper: true
      _06#UICWebCamWidget: false
    - _00div.UICmainTabs: true
      _01#sidebar_plugin_bedlevelingwizard_wrapper: true
    - _00#UICGcodeVWidget: true
      _01#UICTempWidget: true
      _02#sidebar_plugin_action_command_notification_wrapper: true
    theme: discorded
    themeLocal: false
    themeVersion: 0.2.9.8
    topIconSort:
    - navbar_plugin_autobim
    - navbar_plugin_mqttpublish
    - navbar_plugin_prettygcode
    - navbar_plugin_touchui
    - navbar_plugin_wled
    - navbar_plugin_action_command_prompt
    - navbar_plugin_firmwareupdater
    - navbar_plugin_logging_seriallog
    - navbar_plugin_logging_plugintimingslog
    - navbar_plugin_health_check
    - navbar_plugin_PrintJobHistory
    - navbar_plugin_DisplayLayerProgress
    widths:
    - '2'
    - '8'
    - '2'
  virtual_printer:
    _config_version: 1
    enabled: true
  wled:
    _config_version: 1
    connection:
      verify_ssl: false
    effects:
      disconnected:
        settings:
        - brightness: 200
          color_primary: '#ff0000'
          color_secondary: '#000000'
          color_tertiary: '#000000'
          effect: Breathe
          id: '10'
          intensity: 127
          override_on: true
          speed: 127
          unique_id: CcU-Mih1
      failed:
        settings:
        - brightness: 200
          color_primary: '#ff0000'
          color_secondary: '#000000'
          color_tertiary: '#000000'
          effect: Blink
          id: 0
          intensity: 127
          override_on: true
          speed: '243'
          unique_id: 21pW5WCy
      idle:
        settings:
        - brightness: 200
          color_primary: '#26ab40'
          color_secondary: '#000000'
          color_tertiary: '#000000'
          effect: Breathe
          id: '10'
          intensity: 127
          override_on: true
          speed: 127
          unique_id: LD7ashP6
      started:
        enabled: true
        settings:
        - brightness: 200
          color_primary: '#16ff05'
          color_secondary: '#000000'
          color_tertiary: '#000000'
          effect: Solid
          id: 0
          intensity: 127
          override_on: true
          speed: 127
          unique_id: 5N8Sa14y
      success:
        enabled: false
    progress:
      cooling:
        settings:
        - brightness: 200
          color_primary: '#bb2525'
          color_secondary: '#0083f5'
          id: '11'
          override_on: true
          unique_id: argrsh53
      heating:
        settings:
        - brightness: 200
          color_primary: '#ff0000'
          color_secondary: '#7ad7ff'
          id: '12'
          override_on: true
          unique_id: 6eQll-4h
      print:
        settings:
        - brightness: 200
          color_primary: '#00ff04'
          color_secondary: '#000000'
          id: '1'
          override_on: true
          unique_id: yqvg8h0c
printerProfiles:
  default: ender_3_v2
serial:
  baudrate: 250000
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: O0OaB9UwJ114X0ZtTSpBwTjX5tRDjvqA
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
  - bed: 75
    chamber: 0
    extruder: 240
    name: Carbon
webcam:
  ffmpeg: /usr/bin/ffmpeg
