accessControl:
  salt: Rg3iNKCPDkglnv21bRLGsBmLNQ5U1vGj
api:
  key: C063DE8FADEB47EFB26DB3534BDE6A3C
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1653306600
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1646055600
      _plugins:
        read_until: 1655182800
      _releases:
        read_until: 1653386400
  cura:
    cura_engine: null
  discovery:
    publicPort: 80
    upnpUuid: 821d45c6-6e18-4ca0-81a2-a724a1fb7dae
  errortracking:
    unique_id: cf6b49b0-75a4-4e43-856e-9d731af8550c
  gcodeviewer:
    _config_version: 1
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: true
    unique_id: a9562b78-91ce-49b4-8ed0-671df47150fd
  virtual_printer:
    _config_version: 1
printerProfiles:
  default: _default
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: O0OaB9UwJ114X0ZtTSpBwTjX5tRDjvqA
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
webcam:
  ffmpeg: /usr/bin/ffmpeg
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: /webcam/?action=stream
