; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:drybox_oleds_common]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
monitor_speed =  230400
framework = arduino
board_build.filesystem = littlefs
upload_port = COM3
monitor_port = COM4
lib_deps = 
	https://github.com/bblanchon/ArduinoJson.git
	knolleary/PubSubClient@^2.8
	https://github.com/Links2004/arduinoWebSockets.git
	adafruit/Adafruit GFX Library @ ^1.12.3
	olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
	bblanchon/ArduinoJson @ ^7.0.0
	mathieucarbou/ESPAsyncWebServer @ ^3.3.0
	mathieucarbou/AsyncTCP @ ^3.2.0
	adafruit/Adafruit SSD1306@^2.5.15

; [env:drybox_oleds]
; platform = ${common.platform}
; board = ${common.board}
; monitor_speed = ${common.monitor_speed}
; framework = ${common.framework}
; lib_deps = 
; 	${common.lib_deps}
; 	adafruit/Adafruit SSD1306@^2.5.15

